### ISSUE TITLE
New version 0.2.2 - from development branch

### ISSUE THREAD

**Issue by aosunacab** [de4a-wp5/de4a-commons#31]
Please can you publish the v0.2.2 on maven repository based on the changes of the commit [bb31aae](https://github.com/de4a-wp5/de4a-commons/commit/bb31aaeb2e59aee89e87264fe86636545cd2619b)?

**Comment by phax** [comment]
Yes, will do. Also requires the IAL changes. Will try to do it asap

**Comment by phax** [comment]
New version is released. Will be on Maven central in the next couple of minutes
