### ISSUE TITLE
DE4AMarshaller with messages including canonical evidences

### ISSUE THREAD

**Issue by aosunacab** [de4a-wp5/de4a-commons#5]
Hi,

I am trying to use unmarshaller:
`eu.de4a.iem.xml.de4a.DE4AMarshaller.doImResponseMarshaller(aCanonicalEvidenceType)`

In order to make conversions with `ResponseExtractEvidenceType`. My problem is, `IDE4ACanonicalEvidenceType` rigth now it  is not populated with the canonical evidences, so it is not possible to make conversions because, even if you reimplement the marshaller with external canonical evidence XSD, JAXB does not maintains referenced classes on his context, so it throw an error.
At this point, I have two questions:

- I assume that canonical evidences XSDs should be on [XML-schemas project](https://github.com/de4a-wp5/xml-schemas) and it turn JAXB objects, factory objects, classes on context. Also update the de4a-commons project with last updates of XSDs on [XML-schemas](https://github.com/de4a-wp5/xml-schemas)

- ¿There is any work around, to use thoose marshaller utils, until canonical evidences schemes and JAXB objects are on the project?

Sorry in advance if I am missing something.

Thanks.

**Comment by andreasjberg** [comment]
You use the IDE4ACanonicalEvidenceType for the supported CanonicalEvidences from EDE4ACanonicalEvidenceType. You can find an example of it being used in the mock [link to it in the code](https://github.com/de4a-wp5/de4a-connector-mock/blob/7eec61462f6ce3e706bab540a0a7b0936675d250/src/main/java/eu/de4a/connector/mock/controller/DE4AController.java#L96)

**Comment by aosunacab** [comment]
Sure, but the enum only contains:
`T42_COMPANY_INFO_V04`
`T42_COMPANY_INFO_V04`

**Comment by phax** [comment]
Correct, because currently we only support the DBA XSDs in 2 different versions. Further canonical evidences will be added while we go. One of the pilot requirements was to have multiple versions of the XSD available in parallel

**Comment by aosunacab** [comment]
I understand. But we have a test scenario over BirthCertificate canonical evidence. it is not possible to add this evidence?

**Comment by phax** [comment]
Of course it is possible.
Where can we find the XSD?

**Comment by aosunacab** [comment]
There is nothing official yet, but could be useful to have it, maybe we can add a "temporary" XSD?

**Comment by phax** [comment]
Sure. Where can I find the temporary XSDs? I can only include what I am aware of :)

**Comment by aosunacab** [comment]
hehe sure. 
It is in here: [BirthCertificate.xsd](https://github.com/de4a-wp5/xml-schemas/blob/master/XSD/canonical/BirthCertificate/BirthCertificate.xsd)
Taking adventage of this, de4a-commons could be updated with last changes made by Daniel Castro.

Thanks a lot.

**Comment by phax** [comment]
Do you know who is the author of this BirthCertificate XSD? I would have some change requests....

**Comment by aosunacab** [comment]
Myself, it's just a basic schema not going much further. although if you have any improvement or modification, no problem.

**Comment by phax** [comment]
Okay, I made some changes to the XSD (extracted the type of the root element)

**Comment by phax** [comment]
@aosunacab what pilot does this XSD belong to? E.g. DBA is for "4.2" - I'd like to keep this assignment in the code

**Comment by aosunacab** [comment]
I don´t really know, There is no official definition of it, I guess

**Comment by phax** [comment]
I don't think it is a good idea to introduce an "arbitrary" format for testing. The DBA pilot XSD is simple enough, isn't it?

**Comment by aosunacab** [comment]
I think it is not a big deal keep a test scheme until an official definition comes. 
Anyway, it could be possible to update commons project with latest XSDs updates?

**Comment by phax** [comment]
DBA 0.6 was added

**Comment by phax** [comment]
I am in the middle of adding the T4.1-UC1 stuff, so I am leaving this open

**Comment by phax** [comment]
Now the Studying Abroad stuff is contained (T4.1, UC1)
