### ISSUE TITLE
EvidenceTypeIdType and EDE4ACanonicalEvidenceType correlation

### ISSUE THREAD

**Issue by aosunacab** [de4a-wp5/de4a-commons#6]
I would like to pose a situation using JAXB conversion throught the marshaller:
`DE4AMarshaller <ResponseTransferEvidenceType> drImResponseMarshaller ( final IDE4ACanonicalEvidenceType aCanonicalEvidenceType)`

At this point you supose to give an `EDE4ACanonicalEvidenceType` as parameter, which define:
- CanonicalEvidence name
- XSDs resources

So far, it should be any correlation between `EDE4ACanonicalEvidenceType` and `EvidenceTypeIdType`, because when Connector is handling the `ResponseTransferEvidenceType` with any canonical evidence inside, you should choose the rigth `EDE4ACanonicalEvidenceType` regarding the EvidenceTypeIdType requested, otherwhise you couldn´t transform correctly the object with de marshaller mentioned.

In fact, if canonical evidences XSDs are needed to transform objects within Connector, it will depends of them to make it rigth, I mean that Connector, regarding this situation, will be bound into canonical evidences XSDs modifications.

Sorry in advance if I missed something.
Thanks.

**Comment by aosunacab** [comment]
Maybe since [CanonicalEvidenceType](https://github.com/de4a-wp5/xml-schemas/blob/35011f58910b55f8ff9b17bbea6ab34831d7e46e/XSD/de4a/common-types.xsd#L54) turn into "lax" contents, DE4Marshallers won´t need canonical evidences XSDs as a mandatory argument.

**Comment by phax** [comment]
There is a special constant `IDE4ACanonicalEvidenceType.NONE` which returns an empty set for use. Does that help you? Additionally by using an interface you can add your own implementation. If the XSD list is empty, than nothing is added, but if you provide them, they are tested which I think is a good thing.

**Comment by aosunacab** [comment]
Yes, I knew about `IDE4ACanonicalEvidenceType.NONE`, but I am pretty sure that if you are handling a `ResponseTransferEvidenceType` with a canonical evidence inside (XSD list), and you do not pass any scheme, the marshaller crash on conversion. Let me check, but it happen to me before, meanwhile we left the issue open.

**Comment by aosunacab** [comment]
I was testing that approach, and you were right, it does work. I assume that since CanonicalEvidenceType turns into "lax".

Thanks

**Comment by phax** [comment]
Yes correct. Thanks for testing. The switch from `strict` to `lax` lead to this result.
