### ISSUE TITLE
Error list type on Marshaller

### ISSUE THREAD

**Issue by aosunacab** [de4a-wp5/de4a-commons#7]
https://github.com/de4a-wp5/de4a-commons/blob/e4876e9c8867e1a086990f95eddac4277859f37d/de4a-iem/src/main/java/eu/de4a/iem/xml/de4a/DE4AMarshaller.java#L118

Currently the error list type used for validation, comes from `com.helger.commons.error.list.ErrorList`, but should comes from `
eu.de4a.iem.jaxb.common.types.ErrorListType`

It is the type generated for this purpose, I guess

**Comment by phax** [comment]
I decided to remove this method, as it was confusing. The class `DE4AMarshaller` is primarily used to marshal and unmarshal the DE4A objects but not add additional semantic on top of it.
Please use the `GenericJAXBMarshaller` methods like `setValidationEventHandlerFactory` manually to get read and write errors as you like.
