### ISSUE TITLE
Conflict between com.helger and com.helger.commons package

### ISSUE THREAD

**Issue by aosunacab** [de4a-wp5/de4a-commons#9]
I am having severals issues integrating last version of de4-commons on Connector. Since library commons  from com.helger packge was replace by com.helger.commons package, there are been raising many conflicts and problems, because in one hand toop-connector is using commons library from com.helger package, on the other hand, last changes on de4a-commons is using a new commons library from com.helger.commons package, so there are conflictive and duplicate classes.

Toop-connector -> ph-commons v9.5.4 (com.helger package) [Ref. pom](https://github.com/de4a-wp5/toop-connector-ng/blob/e80a3f8894eb836a4cbb72e9c9b18f5ce42a6e32/pom.xml#L92)
de4a-commons -> ph-commons v10.0.0 (com.helger.commons package) [Ref. pom](https://github.com/de4a-wp5/de4a-commons/blob/adce0f80a96ba41c3a795c3b433258d4b73f7e91/de4a-iem/pom.xml#L58)

Thanks

**Comment by phax** [comment]
I know. You need to go to version `2.1.2-SNAPSHOT` of the TOOP-Connector as a quick fix. I will see if I can get a release done of the TOOP Connector to get it fixed.

**Comment by aosunacab** [comment]
Ok, I will try that.

Thanks

**Comment by aosunacab** [comment]
I was checking version 2.1.2-SNAPSHOT and I don´t see commons library update, as far as I understand, toop-connector should handle same common library as de4a-commons project. I didn´t got the work-around.

**Comment by phax** [comment]
There should be. An updated was pushed on March 24th and deployed to https://oss.sonatype.org/content/repositories/snapshots/eu/toop/tc-main/2.1.2-SNAPSHOT/ - please try using `-U` or "Update snapshots" when building. Are you using IntelliJ or Eclipse?
